pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success="Build and Test (ubuntu-latest, 2.12.15, adopt@1.8)"
      - status-success="Build and Test (ubuntu-latest, 2.13.7, adopt@1.8)"
      - body~=labels:.*semver-patch.*
    actions:
      merge:
        method: merge
