version: "3.1"

services:
  db:
    image: mdillon/postgis:11 # postgres with postgis
    environment:
      POSTGRES_DB: world
    ports:
      - 5432:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
